version: "3.8"

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass@word1
      MYSQL_DATABASE: employee_db
    ports:
      - "3307:3306"

  backend:
    build: ./backend/employee
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employee_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pass@word1
    ports:
      - "8082:8081"

  frontend:
    build: ./frontend/employeeweb
    ports:
      - "5173:5173"
